//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoPartApp.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoPart.
        /// </summary>
        public static string AutoPartName {
            get {
                return ResourceManager.GetString("AutoPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Parts.
        /// </summary>
        public static string AutoPartsName {
            get {
                return ResourceManager.GetString("AutoPartsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part 2025.
        /// </summary>
        public static string AutoPartTitle {
            get {
                return ResourceManager.GetString("AutoPartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGN.
        /// </summary>
        public static string BGNName {
            get {
                return ResourceManager.GetString("BGNName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bg-BG.
        /// </summary>
        public static string BulgarianCultureCode {
            get {
                return ResourceManager.GetString("BulgarianCultureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string BulgarianName {
            get {
                return ResourceManager.GetString("BulgarianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearName {
            get {
                return ResourceManager.GetString("ClearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Create Database.
        /// </summary>
        public static string ConfirmCreateDatabaseName {
            get {
                return ResourceManager.GetString("ConfirmCreateDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDeleteName {
            get {
                return ResourceManager.GetString("ConfirmDeleteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database creation canceled..
        /// </summary>
        public static string CreateDatabaseCanceledName {
            get {
                return ResourceManager.GetString("CreateDatabaseCanceledName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create a new database?.
        /// </summary>
        public static string CreateDatabaseQuestionName {
            get {
                return ResourceManager.GetString("CreateDatabaseQuestionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New DataBase.
        /// </summary>
        public static string CreateNewDataBaseName {
            get {
                return ResourceManager.GetString("CreateNewDataBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data to DB tables.
        /// </summary>
        public static string DataAddToDBName {
            get {
                return ResourceManager.GetString("DataAddToDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Import.
        /// </summary>
        public static string DataImportName {
            get {
                return ResourceManager.GetString("DataImportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .csv Data.
        /// </summary>
        public static string DeleteCSVDataName {
            get {
                return ResourceManager.GetString("DeleteCSVDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all imported CSV data?.
        /// </summary>
        public static string DeleteCSVDataQuestionName {
            get {
                return ResourceManager.GetString("DeleteCSVDataQuestionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionName {
            get {
                return ResourceManager.GetString("DescriptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-EN.
        /// </summary>
        public static string EnglishCultureCode {
            get {
                return ResourceManager.GetString("EnglishCultureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        public static string EuroName {
            get {
                return ResourceManager.GetString("EuroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import .csv file.
        /// </summary>
        public static string ImportCSVName {
            get {
                return ResourceManager.GetString("ImportCSVName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Store Qty.
        /// </summary>
        public static string InStoreName {
            get {
                return ResourceManager.GetString("InStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Data.
        /// </summary>
        public static string ModifyDataName {
            get {
                return ResourceManager.GetString("ModifyDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months To Order:.
        /// </summary>
        public static string MonthsToOrderName {
            get {
                return ResourceManager.GetString("MonthsToOrderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed Qty.
        /// </summary>
        public static string NeededQtyName {
            get {
                return ResourceManager.GetString("NeededQtyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Qty.
        /// </summary>
        public static string OrderQtyName {
            get {
                return ResourceManager.GetString("OrderQtyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrdersName {
            get {
                return ResourceManager.GetString("OrdersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string PackageName {
            get {
                return ResourceManager.GetString("PackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part ID.
        /// </summary>
        public static string PartIDName {
            get {
                return ResourceManager.GetString("PartIDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PriceName {
            get {
                return ResourceManager.GetString("PriceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales History.
        /// </summary>
        public static string SaleHistoryName {
            get {
                return ResourceManager.GetString("SaleHistoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Id or Description.
        /// </summary>
        public static string SearchLabelName {
            get {
                return ResourceManager.GetString("SearchLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchName {
            get {
                return ResourceManager.GetString("SearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File to import.
        /// </summary>
        public static string SelectFileName {
            get {
                return ResourceManager.GetString("SelectFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest Orders.
        /// </summary>
        public static string SuggestOrdersName {
            get {
                return ResourceManager.GetString("SuggestOrdersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total BGN.
        /// </summary>
        public static string TotalBGNName {
            get {
                return ResourceManager.GetString("TotalBGNName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Euro.
        /// </summary>
        public static string TotalEuroName {
            get {
                return ResourceManager.GetString("TotalEuroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string WareHouseName {
            get {
                return ResourceManager.GetString("WareHouseName", resourceCulture);
            }
        }
    }
}
